[mongo]
uri = "mongodb+srv://emnamastouri4_db_user:2HvOlDz5sheNPuWi@cluster0.uedglui.mongodb.net/?appName=Cluster0"
[SMTP]
SMTP_USER = "emnamastouri4@gmail.com"
SMTP_PASS = "hrtn lypy kcnt tzpm"

[google_oauth]
GOOGLE_CLIENT_ID ="91058020468-8ahmdj1ldlhip2kkoqrb9t8qq6q7fv8m.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET = "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"
REDIRECT_URI = "http://localhost:8501"

AUTH_URL = "https://accounts.google.com/o/oauth2/v2/auth"
TOKEN_URL = "https://oauth2.googleapis.com/token"
USERINFO_URL = "https://openidconnect.googleapis.com/v1/userinfo"